# Model arguments
overwrite_hub_revision: true
# Data training arguments
model_name_or_path: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28
dataset_name_or_path: /root/LLM-for-legal-frauds/contract_sft/CodingProject4/parsed_llama_training_data_diverse.jsonl
dataset_mode: local


# Training arguments with sensible defaults
# Add other options from here: https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/trainer#transformers.TrainingArguments
bf16: true
do_eval: true
do_train: true
eval_strategy: epoch # One of ["no", "steps", "epoch"]
gradient_accumulation_steps: 2  # Increased for better gradient stability with varying lengths
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.0e-05
log_level: passive
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 3
output_dir: checkpoints  # do not change when submission
hub_model_revision: main
run_name: legal-contract-sft
overwrite_output_dir: true
per_device_eval_batch_size: 4  # Reduced due to variable lengths
per_device_train_batch_size: 2  # Reduced due to variable lengths  
push_to_hub: False
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "no"
seed: 42
wandb_run_group: legal-contract-sft
wandb_run_id: null # Set this to a globally unique string if you want a descriptive name of your run
wandb_tags: # Use tags to filter runs on WandB
- sft
- legal
- contracts
warmup_ratio: 0.1  # Increased warmup for stability
packing: false  # Disable packing to handle variable lengths better